### ISSUE TITLE
APNSwiftConnection has no possibility to configure proxy-server

### ISSUE THREAD

**Issue by SupaBasti** [kylebrowning/APNSwift#104] opened 2021-03-26 11:33 UTC
I just ported my backend from macOS to Ubuntu and since then APNSwiftConnection does not connect anymore. The only thing I see in log file is 

"Connection - starting"

All works fine on macOS so I guess sit might be an issue with a proxy or so. So, how can I configure a proxy here? It seems like the EventLoopFuture<Channel> is not returned from ClientBoostrap.connect.

Sending local curl-command to api.push.apple.com:443 works.

**Comment by VilemKurz** [comment] 2021-03-27 11:33
This might be the root cause: https://github.com/vapor/apns/issues/33 
tldr Apple's certificate is not trusted by default on Ubuntu

**Comment by SupaBasti** [comment] 2021-03-29 07:40
tanks, but the thing is that I CAN connect via curl setting my proxy with https_proxy=... and I do not see ANY errors from SwiftAPNS so my suggestion is that the connection simply does not establish like if you were behind a firewall

**Comment by SupaBasti** [comment] 2021-03-29 07:47
I also tried to configure Proxy for vapor HttpCLient in my configure.swift, but it does not have any effect here:

app.http.client.configuration.proxy = .some(.server(host: "localhost", port: 3128))

**Comment by florianreinhart** [comment] 2021-03-29 15:20
Apple will change the server certificate today: https://developer.apple.com/news/?id=7gx0a2lp

For the sandbox environment they already use a certificate signed by AAA Certificate Services.

**Comment by SupaBasti** [comment] 2021-03-29 15:30
It's not a certificate issue. The problem is that ClientBootstrap in APNSwiftConnection does not support to connect via proxy server but just direct connection

**Comment by kylebrowning** [comment] 2021-03-29 15:36
Hmm, ClientBootstrap doesn't offer anyone to configure a proxy, I believe it is done under the hood. 

Heres an example, which looks almost identical to how we boot up our ClientProxy. 

https://github.com/apple/swift-nio-examples/blob/main/connect-proxy/Sources/ConnectProxy/ConnectHandler.swift#L142

Are you sure this isn't a certificate issue?

**Comment by SupaBasti** [comment] 2021-03-29 15:44
if it was a certificate issue I would expect an error message but in my case just nothing happens and the only log-output I see is "Connection - starting"

**Comment by kylebrowning** [comment] 2021-03-29 15:49
> if it was a certificate issue I would expect an error message but in my case just nothing happens and the only log-output I see is "Connection - starting"

I wouldn't rely too heavily on the logging I've added to cover all use cases for failures. Considering proxy's work on macOS, but not Ubuntu leads me to believe what @VilemKurz said is correct.

**Comment by SupaBasti** [comment] 2021-03-29 15:51
seems like on my macOS the connection to api.push.apple.com:443 can be established directly and WITHOUT proxy. This is the reason for the difference, I guess.

**Comment by SupaBasti** [comment] 2021-03-29 16:07
maybe something like is done here:
https://phoenix.yizimg.com/vapor/http/blob/main/Sources/HTTPKit/Client/HTTPClient.swift

here ClientBootstrap is used with proxy if needed. Please take a look.

**Comment by kylebrowning** [comment] 2021-03-29 16:11
That link doesn't work.

**Comment by kylebrowning** [comment] 2021-03-29 16:14
That looks like vapor 3 and NIO 1

**Comment by SupaBasti** [comment] 2021-03-29 18:41
@florianreinhart says that sandbox already uses AAA certificate but when I try to send PushMessage to sandbox I get the same result.
"Connection - starting" and nothing else happens. For me it still seems a problem of missing proxy possibility.

**Comment by kylebrowning** [comment] 2021-03-29 23:20
OKay @SupaBasti Im talking with the NIO guys on the discord vapor server so may have more information tomorrow

**Comment by SupaBasti** [comment] 2021-03-30 06:51
> OKay @SupaBasti Im talking with the NIO guys on the discord vapor server so may have more information tomorrow

Thanks. Hopefully it can be clarified

**Comment by SupaBasti** [comment] 2021-03-30 08:30
ok, I could make it work by adding a ProxyChannelHandler to tcpConnection like so:

```swift
let tcpConnection = ClientBootstrap(group: eventLoop)
            .channelInitializer { channel in
                return channel.pipeline.addProxyHandler(host: configuration.url.host!, port: 443, authorization: nil)
            }
            .connect(host: "localhost", port: 3128)
```

**Comment by SupaBasti** [comment] 2021-04-12 15:38
@kylebrowning any news on that or about possibility to integrate?

**Comment by kylebrowning** [comment] 2021-04-12 15:38
@SupaBasti Im happy to accept a PR.

**Comment by SupaBasti** [comment] 2021-04-12 17:57
tried to push but get 403 response:
git push --set-upstream origin support_proxy

**Comment by sudo-nautilus** [comment] 2021-08-08 09:09
> maybe something like is done here:
> https://phoenix.yizimg.com/vapor/http/blob/main/Sources/HTTPKit/Client/HTTPClient.swift
> 
> here ClientBootstrap is used with proxy if needed. Please take a look.

Um, do you think that site is really legit (or even legal to use), is it really safe?

**Comment by kurahaupo** [comment] 2021-08-08 14:57
@SupaBasti 
> phoenix.yizimg.com

That's clearly **not** a github URL; please get the real URL and edit your comment.

And then make sure that you log into the real github site, and change your password, since you've just given it away to some hackers in China.

**Comment by sudo-nautilus** [comment] 2021-08-09 02:11
> @SupaBasti
> 
> > phoenix.yizimg.com
> 
> That's clearly **not** a github URL; please get the real URL and edit your comment.
> 
> And then make sure that you log into the real github site, and change your password, since you've just given it away to some hackers in China.

That's it 👍

**Comment by kylebrowning** [comment] 2022-01-03 16:23
IM in the process of moving this client to ASYNCHttpClient which will support proxying.

**Closed by kylebrowning** 2022-01-03 16:23 UTC
